# Generated by Django 4.1 on 2022-09-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='hoursesize',
            new_name='housesize',
        ),
        migrations.RenameField(
            model_name='housing',
            old_name='hoursetype',
            new_name='housetype',
        ),
    ]
