# Generated by Django 4.1 on 2022-09-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_hoursesize_housing_housesize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='master_map',
            field=models.CharField(default=None, max_length=32, verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housing',
            name='area',
            field=models.CharField(max_length=32, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='community',
            field=models.CharField(max_length=64, verbose_name='小区'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='direction',
            field=models.CharField(max_length=32, verbose_name='朝向'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='fitment',
            field=models.CharField(max_length=32, verbose_name='装修格局'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='housesize',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='housetype',
            field=models.CharField(max_length=64, verbose_name='房型'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='plce',
            field=models.CharField(max_length=32, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='position',
            field=models.CharField(max_length=32, verbose_name='地段'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='re_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='tag',
            field=models.TextField(verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='title',
            field=models.CharField(max_length=256, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='平方价'),
        ),
    ]
