# Generated by Django 4.1 on 2022-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_housing_master_map_alter_housing_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='master_map',
            field=models.CharField(max_length=255, verbose_name='图片'),
        ),
    ]
