# Generated by Django 4.1 on 2022-09-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_housing_master_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=32, verbose_name='区')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('community', models.CharField(max_length=64, verbose_name='小区')),
                ('position', models.CharField(max_length=32, verbose_name='地段')),
                ('tag', models.TextField(verbose_name='标签')),
                ('re_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总价')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='平方价')),
                ('housetype', models.CharField(max_length=64, verbose_name='房型')),
                ('housesize', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='面积')),
                ('direction', models.CharField(max_length=32, verbose_name='朝向')),
                ('fitment', models.CharField(max_length=32, verbose_name='装修格局')),
                ('plce', models.CharField(max_length=32, verbose_name='地区')),
                ('master_map', models.CharField(max_length=255, verbose_name='图片')),
            ],
        ),
    ]
