# Generated by Django 4.1 on 2022-09-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_housing_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='housesize',
            field=models.CharField(max_length=32, verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='re_price',
            field=models.CharField(max_length=32, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='unit_price',
            field=models.CharField(max_length=32, verbose_name='平方价'),
        ),
        migrations.AlterField(
            model_name='housing_update',
            name='housesize',
            field=models.CharField(max_length=32, verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='housing_update',
            name='re_price',
            field=models.CharField(max_length=32, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='housing_update',
            name='unit_price',
            field=models.CharField(max_length=32, verbose_name='平方价'),
        ),
    ]
