# Generated by Django 4.1 on 2022-11-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_housing_housesize_alter_housing_re_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='house_id',
            field=models.CharField(default=1, max_length=32, verbose_name='id号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing_update',
            name='house_id',
            field=models.CharField(max_length=32, null=True, verbose_name='id号'),
        ),
    ]
