# Generated by Django 4.1 on 2022-11-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_housing_house_id_housing_update_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='house_id',
            field=models.CharField(default='1', max_length=32, verbose_name='id号'),
        ),
        migrations.AlterField(
            model_name='housing_update',
            name='house_id',
            field=models.CharField(default='1', max_length=32, verbose_name='id号'),
        ),
    ]
